<div id="about">
	<h2>Who We Are</h2>
	<p>
	  We are a group of well trained volunteers that assist in providing communications and emergency response expertise in emergency situations to 
	  agencies like the Denver Office of Emergency Management, Hospitals and others.
	</p>

	<h2>Our Mission</h2>
	<p>
	  The purpose of Denver ARES/CERT is to serve the auxiliary emergency communications and emergency response needs of City and County of Denver.
	  Our primay served agency is the Denver Office of Emergency Managment. The Denver ARES/CERT Emergency Coordinator works to understand the local
	  community's needs and to organize resources to maintain an adequate level of emergency preparedness.
	</p>
	
	<h2>What is ARES?</h2>
	<p>
	  The Amateur Radio Emergency Service (ARES) provides emergency communication support for local government and community service agencies.
	  Currently, the Colorado ARES is divided into 29 districts. Each district has an Emergency Coordinator who works with served agencies (such as
	  police, fire, sheriff, search &amp; rescue, and offices of emergency management) to determine how to best meet the projected emergency 
	  communications needs.
	</p>
	<p>ARES&reg; and Amateur Radio Emergency Service&reg; are registered trademarks of the American Radio Relay League, Inc. and are used by permission</p>
	
	<h2>What is CERT?</h2>
	<p>
	  The <a href="http://fema.gov/" title="FEMA">Federal Emergency Management Agency</a> (course #IS317), using the model created by the Los Angeles
	  Fire Department (LAFD), the <a href="http://www.citizencorps.gov/cert/index.shtm" title="CERT">Community Emergency Response Team</a> concept in
	  1986. Since then, hundreds of communities across the United States have established their own CERT programs.
	</p>
	<p>
	  The City and County of Denver, Mayor's Office of Emergency Management is using the LAFD model to develop Denver's Community Emergency Response
    Training (Denver CERT) as a partnering effort between emergency services and the people they serve. The goal is for emergency personnel to train
    citizens of our community in basic preparedness and skills.
  </p>
	<p>
	  If a disastrous event overwhelms or delays the community professional response, citizens can better protect themselves by applying the preparedness skills that they learned during training. These skills can help save and sustain their lives following a disaster until help arrives. "Denver CERT" skills also apply to daily emergencies.
	</p>
</div>
