<div class="container">
	<div class="row">
		<div class="col-lg-12">
	<h2>Who We Are</h2>
	<p>
	  We are a group of well trained volunteers that assist in providing communications and emergency response expertise in emergency situations to 
	  agencies like the Denver Office of Emergency Management, Hospitals and others.
	</p>

	<h2>Our Mission</h2>
	<p>
	  The purpose of Denver ARES/CERT is to serve the auxiliary emergency communications and emergency response needs of City and County of Denver.
	  Our primay served agency is the Denver Office of Emergency Managment. The Denver ARES/CERT Emergency Coordinator works to understand the local
	  community's needs and to organize resources to maintain an adequate level of emergency preparedness.
	</p>
	
	<h2>What is ARES?</h2>
	<p>
	  The Amateur Radio Emergency Service (ARES) provides emergency communication support for local government and community service agencies.
	  Currently, the Colorado ARES is divided into 29 districts. Each district has an Emergency Coordinator who works with served agencies (such as
	  police, fire, sheriff, search &amp; rescue, and offices of emergency management) to determine how to best meet the projected emergency 
	  communications needs.
	</p>
	<p>ARES&reg; and Amateur Radio Emergency Service&reg; are registered trademarks of the American Radio Relay League, Inc. and are used by permission</p>
		</div>
	</div>
</div>

