<div class="container"><footer>	<div class="row">		<div class="col-lg-12">            <ul class="list-unstyled">				<li class="pull-right"><a href="#top">Back to top</a></li>				<li><a href="/">Home</a></li>				<li><a href="index.php?page=about">About</a></li>				<li><a href="index.php?page=calendar">Calendar</a></li>				<li><a href="index.php?page=join">Join</a></li>				<li><a href="index.php?page=contact">Contact</a></li>			</ul>			<p>&copy 2014 Denver ARES / CERT</p>		</div>	</div></footer>

<!-- Place this tag after the last +1 button tag. --><script type="text/javascript">(function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);})();</script></div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>
