<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Denver ARES and CERT, Serving the City and County of Denver, Colorado</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <!--<link rel="stylesheet" type="text/css" href="/css/style.css">-->
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/css/bootswatch.min.css" />
    </head>
    <body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">Denver ARES and CERT</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
		<ul class="dropdown-menu">
			<li> <a href="index.php?page=about">About</a></li>
			<li><a href="index.php?page=skywarn">Skywarn&reg;</a></li>
		</ul>
            </li>
            <li><a href="index.php?page=training">Training</a></li>
            <li><a href="index.php?page=calendar">Calendar</a></li>
            <li><a href="index.php?page=join">Join</a></li>
	    <li><a href="index.php?page=contact">Contact</a></li>
	  </ul>
        </div>
      </div>
    </div>
