<div id="content">
  <center><img src="images/DenverSkyline.jpg" width="450" /></center>

  <p>We are the Amateur Radio Emergency Service and Community Emergency Response Team serving the City and County of Denver Colorado.</p>
  <p>We are also a part of the North Central Region (NCR) All Hazards Region, serving the citizens and agencies of Adams, Arapahoe, Boulder, Broomfield, Clear Creek, Denver, Douglas, Elbert, Gilpin, and Jefferson Counties.</p>

  <center><img src="images/NCR.jpg" /></center>
</div>
