<div class="container">
	<div class="row">
		<div class="col-lg-9">
			<h1>Denver ARES/CERT</h1>
			<p class="lead">Serving the City and County of Denver, Colorado</p>
			<center><img src="images/DenverSkyline.jpg" width="450" /></center>
			<p>We are the Amateur Radio Emergency Service and Community Emergency Response Team serving the City and County of Denver Colorado.</p>
	<div class="row">
		<div class="col-lg-6">
			<img src="/images/ares-logo.png" class="pull-left" alt="ARES Logo"><p>Denver ARES/CERT is a part of the Rocky Mountain Division, Colorado Section. Our designation is Region 1 District 4.</p>
		</div>
		<div class="col-lg-6">			
<img src="/images/ncr-logo.png" class="pull-left" alt="North Central All HAzards Region Logo"><p>Denver ARES/CERT are also a part of the North Central Region (NCR) All Hazards Region, serving the citizens and agencies of Adams, Arapahoe, Boulder, Broomfield, Clear Creek, Denver, Douglas, Elbert, Gilpin, and Jefferson Counties.</p>
		</div>
	</div>		
</div>
		<div class="col-lg-3" style="margin-top: 30px;">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">New HAM or CERT?</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="input-group">
                            <p><a href="/?page=gettingstarted">Getting started with ARES/CERT</a></p>
                        </div>
                    </div>
                </div>
            </div>
		
			<div class="panel panel-primary">
			  <div class="panel-heading">
				<h3 class="panel-title">Upcoming Events</h3>
			  </div>
			  <div class="panel-body">
				<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=denverdistrict13%40gmail.com&amp;color=%23875509&amp;ctz=America%2FDenver" width="230" height="400" frameborder="0" scrolling="no"></iframe>
			  </div>
			</div>
			<div class="panel panel-primary">
			  <div class="panel-heading">
				<h3 class="panel-title">QRZ Lookup</h3>
			  </div>
			  <div class="panel-body">
				<div class="form-group">
				  <div class="input-group">
					<form action="http://www.qrz.com/db/" method="GET">
					    <input class="form-control" type="text" name="callsign" style="width: 10em;" />
					    <span class="input-group-btn">
						<input class="btn btn-primary" type="submit" value="Search"/>
					    </span>
					</form>
				  </div>
				</div>
			 </div>
			</div>
		</div>
	</div>
</div>
