<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h2>Join Us</h2>
				<p>Denver ARES and CERT is always looking for volunteers to assist us in helping the public.</p>
				
					<p>To register, please download and fill out the <a href="DAC-regform-0314.pdf">Denver ARES/CERT Registration Form</a> and email it to us at <a href="mailto:kc0mht@msn.com">this address</a> or bring it with you to your Ham class, CERT class, or our next face-to-face meeting (See our <a href="index.php?page=calendar">Calendar</a> for dates).
			<p>For more information, please <a href="/index.php?page=contact">contact us.</a>
	</div>
	</div>
</div>
