<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h2>Join Us</h2>
				<p>Please contact <a href="mailto:denverdistrict13@gmail.com">denverdistrict13@gmail.com</a> for more information.</p>
				<div id="registration">
					<p>To register, please download and fill out the <a href="DAC-regform-0314.pdf">Denver ARES/CERT Registration Form</a> and email it to us at <a href="mailto:kc0mht@msn.com">this address</a> or bring it with you to your Ham or CERT class or our next face to face meeting <a href="index.php?page=calendar">Calendar</a>
				</div>
		</div>
	</div>
</div>
