<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h2>Join Us</h2>
				<p>Denver ARES is always looking for volunteers to assist us in helping the public.</p>
				<p>Registration is a simple 3 step process.</p>
				<h3>1. Complete and return our registration form</h3>
					<p>To register, please download and fill out the <a href="DAC-regform-0314.pdf">Denver ARES Registration Form</a> and either scan and email it to us at <a href="mailto:online@denver-ares-cert.org">online@denver-ares-cert.org</a> or bring it with you to your ham class, CERT class, or our next face-to-face meeting (See our <a href="index.php?page=calendar">Calendar</a> for dates).
				<h3>2. Signup to the mailing list</h3>
				<p>Head over to the <a href="https://groups.google.com/forum/#!forum/denver-ares-cert-main">Denver ARES mailing list</a> and register yourself.</p>
				<h3>3. Register with the Colorado Volunteer Mobilizer</h3>
				<p>To register with the <a href="https://covolunteers.state.co.us/">Colorado Volunteer Mobilizer</a> you will need to provide the following:</p>
					<ol>
						<li>ICS-100 certificate of completion</li>
						<li>ICS-700 certificate of completion</li>
						<li>Details to submit a background check</li>
					</ol>
				<p>More information about the required training certificates can be found in the <a href="/index.php?page=training">Training</a> section.</p>
				<p>When registering, add yourself to the "Colorado ARES Organization &gt; Region 1 (North Central) &gt; Dist 4 Denver City/County" organization</p>
				<img src="/images/cvm-org.png" alt="Colorado ARES Organization &gt; Region 1 (North Central) &gt; Dist 4 Denver City/County organization" />
	</div>
	</div>
</div>
