<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1>Radio Net Information</h1>
			<p>Our weekly ARES District Radio Net is conducted every Sunday at 1800 (6:00pm) local time on the following repeater  frequencies:</p>
			<ul>
				<li>146.670- PL100 courtesy of the <a href="http://www.crrg.org/">Castle Rock Repeater Group</a></li>
				<li>(Backup) 145.490- PL100 courtesy of the <a href="http://www.w0tx.org/">Denver Radio Club</a></li>
			</ul>
			<p>If both repeaters are down, our simplex frequency is 146.460.</p>

</div>
</div>
</div>
