<div id="news">
	<a class="twitter-timeline" href="https://twitter.com/ARESDistrict13" data-widget-id="264162438876893184">Tweets by @ARESDistrict13</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>