
<div id="right">

	<div id="badges">
		<img src="images/ares-sm.jpg" alt="ARES Logo"><br/>
		<img src="images/cert-sm.jpg" alt="CERT Logo">
	</div>
	
	<div id="social_buttons">
		<h4>Be a fan of Denver ARES/CERT</h4>
		
		<!-- Insert the Twitter Follow button -->
		<a href="https://twitter.com/DenverAresCert" class="twitter-follow-button" data-show-count="false">Follow @DenverAresCert</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		
		<p/>
		
		<!-- Insert the Facebook Like button -->
		<div class="fb-like" data-href="https://www.facebook.com/DenverDistrict13" data-send="false" data-width="225" data-show-faces="true"></div>
		
		<p/>

    <!-- Place this tag where you want the +1 button to render. -->
    <div class="g-plusone"></div>
  </div>
		
	<!-- Show NTAS widget -->
	<iframe name="National Terrorism Advisory System" border="0" width="170" height="180" scrolling="no" src="http://www.dhs.gov/ntas/"></iframe>
	
</div>
