<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1>About Skywarn&reg;</h1>

			<img src="/images/skywarn-logo.gif" alt="Skywarn&reg; Logo" class="pull-right">
			<h2>What is Skywarn&reg;?</h2>
			<p>Started in the 1970's, the National Weather Service's (NWS) Skywarn&reg; program trains regular citizens in basic meteoriological concepts around severe weather and its development. Trained weather spotters provide "ground truth" to help forecasters in their decision to issue weather advisories.</p>

			<h2>Denver ARES and CERT's Role</h2>
			<p>Denver ARES and CERT is responsible for providing Skywarn&reg; radio nets for the city and county of Denver during times of severe weather. Our job is to act as communicators between spotters in the field and the Warning Coordination Meteorologist at the NWS field office in Boulder.</p>
			<h2>How do I become a Skywarn&reg; weather spotter?</h2>
			<p>Skywarn&reg; weather spotter training is provided by the NWS at various times throughout the year. The total couse takes around three hours to complete and is provided free of charge.</p>
			<p>Upon successful completion of the Skywarn&reg; training you will be issued with a unique spotter number. This number is used when making reports to the NWS.</p>
			<p>Details about upcoming training are available at the <a href="http://www.crh.noaa.gov/bou/?n=spot_training">Denver/Boulder NWS Spotter Training</a> page</p>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">More information</h3>
  </div>
  <div class="panel-body"> 
	<ul>
		<li><a href="http://www.nws.noaa.gov/skywarn/">NWS Skywarn</a></li>
		<li><a href="http://skywarn.org/">Skywarn National</a></li>
	</ul>
	  </div>
</div>


			<p>Skywarn® and the Skywarn® logo are registered trademarks of the National Oceanic and Atmospheric Administration, used with permission.</p>
</div>
</div>
</div>
