<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1>Training</h1>
	<h3>Essential Training for all ARES/CERT personnel</h3>
	<p>The following courses are all offered free or charge and on-demand:</p>
	<ul>
		<li><a href="http://training.fema.gov/EMIWeb/IS/courseOverview.aspx?code=IS-100.b">IS-100.B: Introduction to Incident Command System, ICS-100</a></li>
		<li><a href="http://training.fema.gov/EMIWeb/IS/courseOverview.aspx?code=is-200.b">IS-200.B: ICS for Single Resources and Initial Action Incidents</a></li>
		<li><a href="http://training.fema.gov/EMIWeb/IS/courseOverview.aspx?code=IS-700.a">IS-700.A: National Incident Management System (NIMS) An Introduction</a></li>
		<li><a href="http://training.fema.gov/EMIWeb/IS/courseOverview.aspx?code=IS-800.b">IS-800.B: National Response Framework, An Introduction</a></li>
	</ul>
	<p>The following course is free of charge and available at select times throughout the year:</p>
	<ul>
		<li><a href="http://www.denvergov.org/oem/OfficeofEmergencyManagement/Programs/DenverCommunityEmergencyResponseTraining/tabid/426128/Default.aspx">Denver Community Emergency Response Training</a></li>
	</ul>



	<h3>Recommended training for ARES personnel</h3>
	<p>The following course is availble for a fee at select times throughout the year</p>
	<ul>
		<li><a href="http://www.arrl.org/online-course-catalog">ARRL - Introduction to Emergency Communication (EC-001)</a></li>
		<li><a href="http://www.crh.noaa.gov/bou/?n=spot_training">Skywarn&reg; Spotter Training</a></li>
	</ul>

	<h3>Recommended training for ARES/CERT leadership</h3>
	<p>The following course is availble for a fee and on-demand</p>
	<ul>
		<li><a href="http://www.arrl.org/ec-016-course">ARRL - Public Service and Emergency Communications Management for Radio Amateurs (EC-016) Course</a></li>
	</ul>
</div>
</div>
</div>
